### ISSUE TITLE
"Missing location usage description values in Info.plist" even if it isn't the case.

### ISSUE THREAD

**Issue by Blaxou** [loup-v/geolocation#22]
So I changed my `Info.plist` file like explained in the README : 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>I need you I need you I need you right now</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>tplusg</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

But it throws me this error saying it can't find the  location usage description values in Info.plist :

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
Geolocation error: Missing location usage description values in Info.plist. See readme for details.
#0      _JsonCodec.resultErrorFromJson (file:///Users/gaetan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-0.2.1/lib/channel/codec.dart:70:7)
#1      _JsonCodec.resultFromJson (file:///Users/gaetan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-0.2.1/lib/channel/codec.dart:47:33)
#2      _Codec.decodeResult (file:///Users/gaetan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-0.2.1/lib/channel/codec.dart:8:18)
#3      _LocationChannel.isLocationOperational (file:///Users/gaetan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-0.2.1/lib/channel/location_channel.dart:37:19)
<asynchronous suspension>
#4      Geolocation.isLocationOperational (package:geolocation/geolocation.dart:46:24)
#5      _StopsAroundPageState.checkGPS (file:///Users/gaetan/Developer/tplusg/lib/views/tabs/around.da<…>

```

**Am I doing something wrong ?**

**Comment by lukaspili** [comment]
1. Do you request permission `whenInUse` or `always`?
2. Did you add the declaration to the correct plist file located at: `ios/Runner/Info.plist`?

**Comment by acudworth** [comment]
Getting this too despite having added the correct privacy statement to `Info.plist`. I'm also requesting `whenInUse` only.

**Comment by shehabic** [comment]
Add the following and it'll work:

```
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Your description here ....</string>
```
