### ISSUE TITLE
enableLocationServices Is not working for ios

### ISSUE THREAD

**Issue by oddillio** [loup-v/geolocation#63]
I get MissingPluginException when i call  Geolocation.enableLocationServices()

flutter: location result: invoke geolocation/location->enableLocationServices []
flutter: ══╡ EXCEPTION CAUGHT BY GEOLOCATION ╞═══════════════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown while invoking
flutter: geolocation/location/enableLocationServices:
flutter: MissingPluginException(No implementation found for method enableLocationServices on channel
flutter: geolocation/location)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
flutter: <asynchronous suspension>
flutter: #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
flutter: #2      _invokeChannelMethod (package:geolocation/channel/helper.dart:12:26)
flutter: #3      _LocationChannel.enableLocationServices (package:geolocation/channel/location_channel.dart:60:28)
flutter: #4      Geolocation.enableLocationServices (package:geolocation/geolocation.dart:55:24)
flutter: #5      _MyAppState.enableLocationServices (package:geolocation_example/main.dart:80:17)
flutter: #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:14)
flutter: #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
flutter: #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
flutter: #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
flutter: #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
flutter: #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
flutter: #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
flutter: #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
flutter: #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
flutter: #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
flutter: #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
flutter: #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
flutter: #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #26     _invoke1 (dart:ui/hooks.dart:275:10)
flutter: #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**Comment by tarafat** [comment]
How did you solved it?
